### ISSUE TITLE
Unverified Breakpoint message while trying to debug tsx file.

### ISSUE THREAD

**Issue by sreeraj-rajendran** [microsoft/azure-devops-extension-hot-reload-and-debug#13]
I am new to this, and have followed the steps. The debugging session starts fine, but if I try to add break points in my tsx file, it shows "Unverified Breakpoint" and the breakpoints are not hit.

![image](https://user-images.githubusercontent.com/48437880/87153721-8b5a6080-c2d5-11ea-83ce-829aca238e56.png)

The .vscode folder and launch.json are at the root, and I have a src folder inside it which had the code files.
Folder structure:
![image](https://user-images.githubusercontent.com/48437880/87154232-7cc07900-c2d6-11ea-9cfd-e9cb7dba44e0.png)

webpack.config.js:
![image](https://user-images.githubusercontent.com/48437880/87154370-bdb88d80-c2d6-11ea-8a58-f4acefe7d13a.png)

launch.json is exactly as mentioned:
`{
    "version": "0.2.0",
    "configurations": [
      {
        "name": "Launch Firefox",
        "type": "firefox",
        "request": "launch",
        "url": "https://localhost:3000/",
        "reAttach": true,
        "pathMappings": [
          {
            "url": "webpack:///",
            "path": "${workspaceFolder}/"
          }
        ]
      }
    ]
  }`

Any hep will be appreciated.

**Comment by AnujEddie** [comment]
Hi, I have the same issue. Says "Unverified breakpoint"

**Comment by karelkral** [comment]
In my experience, breakpoints behave very randomly in DevOps Plugin. Especially when the breakpoint is placed in code called early on plugin startup, execution is stopped on breakpoint very randomly. This is very frustrating thing. Try reload the page and (in my case) after 20 reload, some times the breakpoint is hit.

Another reason may be that your code and the code produced by webpack are out-of sync. Here I stop WebPack in terminal window by hitting Ctrl-C and run "npm run start" again. This works most of the time.

**Comment by MatisseHack** [comment]
Breakpoints can be a bit finicky on first load. They tend to work well for me once everything is running. Sounds like it might be somewhat system dependent though.

Can you try cloning a fresh copy of this repo? I just cloned a fresh copy and was able to debug **src/hub/hub.tsx** by navigating to <https://localhost:3000/dist/hub/hub.html>. I had to reload the page once, but debugging worked consistently after that.
