### ISSUE TITLE
yo @microsoft/azure-devops-extension fails

### ISSUE THREAD

**Issue by stefanstranger** [microsoft/azure-devops-extension-hot-reload-and-debug#2]
When I run yo @microsoft/azure-devops-extension it fails with the following error:

```
AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:\Users\johndoe\AppData\Roaming\npm\node_modules\@microsoft\generator-azure-devops-extension\app\templates\.gitignore
```
After creating manually a .gitignore file in the C:\Users\johndoe\AppData\Roaming\npm\node_modules\@microsoft\generator-azure-devops-extension\app\templates folder I could create the scaffolding for the Extension.

Stefan [msft]

**Comment by MatisseHack** [comment]
Good catch! It seems npm renames `.gitignore` to `.npmignore` when it installs the package. Should be fixed by microsoft/azure-devops-extension-yeoman-generator#2 (published in version 1.0.1)
