### ISSUE TITLE
Old dependencies

### ISSUE THREAD

**Issue by johnnyreilly** [microsoft/azure-devops-extension-hot-reload-and-debug#24]
Hello!

I've just happened upon this repo (guided by [this post](https://devblogs.microsoft.com/devops/streamlining-azure-devops-extension-development/)) and I was wondering if there was any reason that the dependencies seem quite old?

https://github.com/microsoft/azure-devops-extension-hot-reload-and-debug/blob/44c5189659fa8e106892b7e1812df19f9848c59f/package.json#L46

TypeScript is up to version 4.2 - is there any reason we need to stick with an older version?

**Comment by MatisseHack** [comment]
Everything should work with updated versions!

Since this is a template repo (rather than a project under active development), we don't often go back to update versions. I would be happy to merge a PR that updates everything though!

**Comment by johnnyreilly** [comment]
Thanks @MatisseHack! I'm hoping to dip my toes into the water of extension development soon.  Who knows, a PR could follow!

**Comment by GaTechThomas** [comment]
An update to versions, say, once every 6 months (preferrably quicker), would be hepful.
