### ISSUE TITLE
Problem with new Extension

### ISSUE THREAD

**Issue by mwawrzyniiak** [microsoft/azure-devops-extension-hot-reload-and-debug#41]
Hi!
I try to create new extension base on this repo. 
My problem is during 'npm install'.
I have a problem with sass.
When I change version on: 7.0.1 I have another problems.
Has anybody tried to create azure-devops-extension (in the last few months) based on this repo?

**Comment by karelkral** [comment]
As I remember, I have a problem with sass also. So I stuck with the older version.  Dependencies and their versions are very fragile thing when developing these extensions :-(
Here are my dependencies from package.json (from my current project, much bigger than this, but you can take version numbers from here).
```
  "dependencies": {
    "@microsoft/applicationinsights-react-js": "^3.2.4",
    "@microsoft/applicationinsights-shims": "^2.0.1",
    "@microsoft/applicationinsights-web": "^2.7.4",
    "@types/history": "^5.0.0",
    "@webpack-cli/init": "^1.1.3",
    "axios": "^0.26.1",
    "azure-devops-extension-api": "^1.158.0",
    "azure-devops-extension-sdk": "^2.0.11",
    "azure-devops-ui": "^2.167.31",
    "dotenv": "^16.0.0",
    "linq-es2015": "^2.5.1",
    "lodash": "^4.17.21",
    "moment": "^2.29.2",
    "query-string": "^7.1.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
	"react-minimal-pie-chart": "^8.2.0",
    "rsdi": "^1.0.11",
    "typescript-string-operations": "^1.4.1"
  },
  "devDependencies": {
    "@types/jest": "^27.4.1",
    "@types/lodash": "^4.14.181",
    "@types/react": "^17.0.43",
    "@types/react-dom": "^17.0.14",
    "@types/sass": "^1.43.1",
    "@typescript-eslint/eslint-plugin": "^5.18.0",
    "@typescript-eslint/parser": "^5.18.0",
    "base64-inline-loader": "^2.0.1",
    "copy-webpack-plugin": "^10.2.4",
    "cross-env": "^7.0.3",
    "css-loader": "^5.2.7",
    "dotenv-webpack": "^7.1.0",
    "eslint": "^8.12.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.0.0",
    "file-loader": "^6.2.0",
    "jest": "^27.5.1",
    "jest-theories": "^1.5.1",
    "prettier": "^2.6.2",
    "rimraf": "^3.0.2",
    "sass": "^1.49.11",
    "sass-loader": "^12.6.0",
    "style-loader": "^3.3.1",
    "tfx-cli": "^0.11.0",
    "ts-jest": "^27.1.4",
    "ts-loader": "^9.2.8",
    "tslint": "^5.20.1",
    "typescript": "^4.6.3",
    "webpack": "^5.71.0",
    "webpack-cli": "^4.9.2",
    "webpack-dev-server": "^4.7.4"
  }
```
`

**Comment by mwawrzyniiak** [comment]
Hi!
Thanks for answer! 
I will try this tomorrow! 
Microsoft should update the documentation and part of the repo that are already available...

**Comment by gioce90** [comment]
I'm trying to develop an extension, a task for a release pipeline, but I'm finding it really difficult to do so. Has anyone had the same experience?

**Comment by mwawrzyniiak** [comment]
@gioce90 
try this:
`  "dependencies": {
    "azure-devops-extension-api": "^1.152.0",
    "azure-devops-extension-sdk": "^2.0.7",
    "azure-devops-ui": "^1.152.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },
  "devDependencies": {
    "@types/react": "^16.8.18",
    "@types/react-datepicker": "^4.4.1",
    "@types/react-dom": "^16.8.4",
    "@typescript-eslint/eslint-plugin": "^1.9.0",
    "@typescript-eslint/parser": "^1.9.0",
    "base64-inline-loader": "^2.0.1",
    "copy-webpack-plugin": "^10.2.4",
    "css-loader": "^5.2.7",
    "eslint": "^5.16.0",
    "eslint-config-prettier": "^4.3.0",
    "eslint-plugin-prettier": "^3.1.0",
    "file-loader": "^6.2.0",
    "prettier": "^2.6.2",
    "react-datepicker": "^4.8.0",
    "rimraf": "^3.0.2",
    "sass": "^1.49.11",
    "sass-loader": "^12.6.0",
    "style-loader": "^3.3.1",
    "tfx-cli": "^0.11.0",
    "ts-loader": "^9.2.8",
    "typescript": "^4.6.3",
    "webpack": "^5.72.1",
    "webpack-cli": "^4.9.2",
    "webpack-dev-server": "^4.9.0"`
